package com.mscncn.cxf.chapter01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-06-11T23:19:18.485+08:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://chapter01.cxf.mscncn.com/", name = "HelloWorldImplPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldImplPortType {

    @WebResult(name = "return", targetNamespace = "http://chapter01.cxf.mscncn.com/")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://chapter01.cxf.mscncn.com/", className = "com.mscncn.cxf.chapter01.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://chapter01.cxf.mscncn.com/", className = "com.mscncn.cxf.chapter01.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "name", targetNamespace = "http://chapter01.cxf.mscncn.com/")
        java.lang.String name
    );
}
