package com.mscncn.cxf.chapter01;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-06-11T23:19:18.495+08:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "HelloWorldImpl", 
                  wsdlLocation = "file:/Users/king-pan/Documents/workspace-sts-3.6.4.RELEASE/cxf-chapter01-client/src/main/resources/helloworld.wsdl",
                  targetNamespace = "http://chapter01.cxf.mscncn.com/") 
public class HelloWorldImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://chapter01.cxf.mscncn.com/", "HelloWorldImpl");
    public final static QName HelloWorldImplPort = new QName("http://chapter01.cxf.mscncn.com/", "HelloWorldImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/king-pan/Documents/workspace-sts-3.6.4.RELEASE/cxf-chapter01-client/src/main/resources/helloworld.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorldImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/king-pan/Documents/workspace-sts-3.6.4.RELEASE/cxf-chapter01-client/src/main/resources/helloworld.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloWorldImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWorldImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWorldImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloWorldImplPortType
     */
    @WebEndpoint(name = "HelloWorldImplPort")
    public HelloWorldImplPortType getHelloWorldImplPort() {
        return super.getPort(HelloWorldImplPort, HelloWorldImplPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldImplPortType
     */
    @WebEndpoint(name = "HelloWorldImplPort")
    public HelloWorldImplPortType getHelloWorldImplPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldImplPort, HelloWorldImplPortType.class, features);
    }

}
